const AUTHENTICATED_ROLE = "AUTHENTICATED_ROLE";

const SUPER_ADMIN_ROLE = "SUPER_ADMIN";
const ADMIN_ROLE = "ADMIN";

const INTERNAL_USER_ROLE = "INTERNAL_USER";
const USER_ROLE = "USER";

export {
  AUTHENTICATED_ROLE,
  SUPER_ADMIN_ROLE,
  ADMIN_ROLE,
  INTERNAL_USER_ROLE,
  USER_ROLE,
};
